apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "http-server.fullname" . }}-html
  labels:
    {{- include "http-server.labels" . | nindent 4 }}
data:
{{- range $fileName, $contents := .Values.htmlFolder }}
  {{ $fileName }}: |
{{ (tpl $contents $) | indent 4 }}
{{- end }}